export const STATUS_CODES = {
    SUCCESS:'200',
    DATA_INSERTED:'201',
    DATA_UPDATED:'202',
    TOKEN_MISSING:'203',
    DATASET_NOT_FOUND:'204',
    ALREADY_REGISTERED:'205',
    INSTAMOJO_PAYMENT_URL_ERROR:'206',
    PASSWORD_DOES_NOT_MATCHED:'207',
    EMAIL_NOT_SEND:'208',
    NOT_ACCESS_TO_THE_GIVEN_USERNAME:'209',
    INVALID_DATA:'210',
    INTERNAL_SERVER_ERROR:'500',
    DATABASE_CONNECTION_ERROR:'501',
    DATABASE_RUNTIME_ERROR:'502'
}